<a href="https://colab.research.google.com/github/Yitzkak/keras-first/blob/master/firstKerasModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

a = np.arange(9).reshape(3,3)

In [2]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
